Create login screen
Super-Patos-Hackaton/frontend pull request #21
Opened 2024-06-18 20:46 UTC by roberto-juniorjp

## Description
Made the login page and required files. Also made specific components for the left column phrase and the authentication form. Lastly, the folders for auth structure were made so the recovery page can fit along.

## Todo
- [ ] Should have an email input field
- [ ] Should have a password input field
- [ ] Should have a login button
- [ ] Should have form validation implemented (e.g., required fields, email format)

## Not ready yet
Still have to do the unit test. Haven't touched that yet.

2024-06-19 15:53 UTC, roberto-juniorjp commented
All features done. It's ready to merge as soon as reviews are done.
@whyleonardo @RO-HSA

2024-06-19 19:47 UTC, RO-HSA commented on src/app/(auth)/_components/loginAuthForm.tsx
> +        <Input
Está faltando validação de formulário

2024-06-19 21:09 UTC, roberto-juniorjp commented
Added zod + dependencies and made the form validations.

2024-06-19 21:34 UTC, RO-HSA requested changes
Make these changes please

2024-06-19 21:34 UTC, RO-HSA commented on src/app/(auth)/_components/recoveryAuthForm.tsx
> +      <Input
Mesma coisa do login, mas vejam se vale a pena, porque é uma feature para melhorar UX

2024-06-19 21:34 UTC, RO-HSA commented on src/app/(auth)/login/page.tsx
> +'use client';
Como não estamos usando hooks no page, remove o use client.

2024-06-19 21:34 UTC, RO-HSA commented on src/app/(auth)/layout.tsx
> +import Image from 'next/image';
Image não está sendo utilizado em lugar nenhum

2024-06-19 21:34 UTC, RO-HSA commented on src/app/(auth)/layout.tsx
> +import { Typography } from '@/components/ui/typography';
Typography não está sendo utilizado em lugar nenhum

2024-06-19 21:34 UTC, RO-HSA commented on src/app/(auth)/layout.tsx
> +import logo from '/public/img/logo.png';
logo não está sendo utilizado em lugar nenhum

2024-06-20 00:12 UTC, RO-HSA approved these changes

2024-06-20 09:31 UTC, RO-HSA submitted a review, later dismissed
lgtm

2024-06-20 12:05 UTC, RO-HSA approved these changes
LGTM

2024-06-20 12:23 UTC, merged